"""Tambah kolom Kode_Pemesanan ke tabel pemesanan

Revision ID: 0a40710f3cb0
Revises: 
Create Date: 2025-11-16 07:02:25.361659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a40710f3cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_pemesanan')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('jobs_queue_index'))

    op.drop_table('jobs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sessions_last_activity_index'))
        batch_op.drop_index(batch_op.f('sessions_user_id_index'))

    op.drop_table('sessions')
    op.drop_table('migrations')
    op.drop_table('cache')
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('failed_jobs_uuid_unique'))

    op.drop_table('failed_jobs')
    op.drop_table('pengguna')
    op.drop_table('cache_locks')
    op.drop_table('password_reset_tokens')
    op.drop_table('job_batches')
    with op.batch_alter_table('jadwal', schema=None) as batch_op:
        batch_op.alter_column('Waktu_Pemberangkatan',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('Waktu_Tiba',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('Harga',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('Kursi_Tersedia',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('kursi', schema=None) as batch_op:
        batch_op.alter_column('Nomor_Kursi',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('Status_Pemesanan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Kode_Pemesanan', sa.String(length=10), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
        batch_op.alter_column('Id_Jadwal',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('Id_Kursi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('Tanggal_Pemesanan',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('Total_Harga',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_unique_constraint(None, ['Kode_Pemesanan'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('remember_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('remember_token', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('user_id'), ['user_id', 'Id_Jadwal', 'Id_Kursi'], unique=True)
        batch_op.alter_column('Total_Harga',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('Tanggal_Pemesanan',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('Id_Kursi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('Id_Jadwal',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
        batch_op.drop_column('Kode_Pemesanan')

    with op.batch_alter_table('kursi', schema=None) as batch_op:
        batch_op.alter_column('Status_Pemesanan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('Nomor_Kursi',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)

    with op.batch_alter_table('jadwal', schema=None) as batch_op:
        batch_op.alter_column('Kursi_Tersedia',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('Harga',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('Waktu_Tiba',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('Waktu_Pemberangkatan',
               existing_type=mysql.TIME(),
               nullable=False)

    op.create_table('job_batches',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('total_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pending_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failed_job_ids', mysql.LONGTEXT(), nullable=False),
    sa.Column('options', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('cancelled_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('finished_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cache_locks',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expiration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pengguna',
    sa.Column('Id_Pengguna', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Nama', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Kata_Sandi', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('Telepon', mysql.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('Id_Pengguna'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('connection', mysql.TEXT(), nullable=False),
    sa.Column('queue', mysql.TEXT(), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('failed_jobs_uuid_unique'), ['uuid'], unique=True)

    op.create_table('cache',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('expiration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(), nullable=True),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('last_activity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sessions_user_id_index'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('sessions_last_activity_index'), ['last_activity'], unique=False)

    op.create_table('jobs',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('queue', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(), nullable=False),
    sa.Column('attempts', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('reserved_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('available_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('jobs_queue_index'), ['queue'], unique=False)

    op.create_table('detail_pemesanan',
    sa.Column('Id_Detail', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Id_Pemesanan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Id_Kursi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Nama_Penumpang', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('No_Identitas', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Detail'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
